version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      
jobs:
  build:
    working_directory: ~/TicketingRest
    
docker:
      - image: circleci/openjdk:8-jdk-stretch
     
steps:

      - checkout

      - restore_cache:
          key: TicketingRest-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: TicketingRest-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/TicketingRest-0.0.1-SNAPSHOT.jar
